module.exports = {
  apps: [
    {
      name: "webhook-dev",
      script: "./server.js",
      instances: 1,
      exec_mode: "fork",
      watch: false, // Set to true for development if needed
      max_memory_restart: "500M",
      env: {
        NODE_ENV: "development",
        PORT: 3010,
      },
      env_production: {
        NODE_ENV: "production",
        PORT: 3011,
      },
      error_file: "./logs/pm2-error.log",
      out_file: "./logs/pm2-out.log",
      log_file: "./logs/pm2-combined.log",
      time: true,
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      restart_delay: 4000,
      kill_timeout: 5000,
      wait_ready: true,
      listen_timeout: 10000,
    },
    {
      name: "webhook",
      script: "./server.js",
      instances: 1,
      exec_mode: "fork",
      watch: false,
      max_memory_restart: "500M",
      env: {
        NODE_ENV: "production",
        PORT: 3011,
      },
      error_file: "./logs/pm2-error-prod.log",
      out_file: "./logs/pm2-out-prod.log",
      log_file: "./logs/pm2-combined-prod.log",
      time: true,
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      restart_delay: 4000,
      kill_timeout: 5000,
      wait_ready: true,
      listen_timeout: 10000,
    },
  ],
};
